### ISSUE TITLE
Crash App in setFirebaseAppId : android

### ISSUE THREAD

**Issue by h2soheili** [metrixorg/MetrixSDK-ReactNativePlugin#5]
مث سمپل این ریپو و داکویمنت ها پروژه رو ستاپ کردیم .همه چی خوبه تا وقتی که 
setFirebaseAppId
رو روی کانفیگ اضافه می کنیم.

```
"@react-native-firebase/analytics": "^6.7.1",
"@react-native-firebase/app": "^6.7.1",
"@react-native-firebase/crashlytics": "^6.7.1",
"@react-native-firebase/iid": "^6.7.1",
"@react-native-firebase/in-app-messaging": "^6.7.1",
"@react-native-firebase/messaging": "^6.7.1",
"@react-native-firebase/perf": "^6.7.2",
"react": "^16.11.0",
"react-native": "^0.62.2",
"@metrixorg/react-native-metrix": "^0.15.2",
```

```
  ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "17.0.0"
        multiDexEnabled = true
    }

```
```
dependencies {
  implementation 'com.google.firebase:firebase-messaging:18.0.0'
  ...
}
```

`rnfirebase android`

```
plugins {
  id "io.invertase.gradle.build" version "1.4"
}

project.ext {
  set('react-native', [
    versions: [
      android : [
        minSdk    : 16,
        targetSdk : 28,
        compileSdk: 28,
        // optional as gradle.buildTools comes with one by default
        // overriding here though to match the version RN uses
        buildTools: "28.0.3"
      ],

      firebase: [
        bom: "24.1.0",
      ],
    ],
  ])
}
```

```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Memory: 127.46 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

```

 --------- beginning of crash
2020-06-24 11:29:57.886 4777-4886/com.daapapp.crmrn E/AndroidRuntime: FATAL EXCEPTION: logThread
    Process: com.daapapp.crmrn, PID: 4777
    java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source)
        at com.google.firebase.iid.FirebaseInstanceId.zza(com.google.firebase:firebase-iid@@20.2.1:52)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.1:2)
        at ir.metrix.sdk.i.a()
        at ir.metrix.sdk.i.v()
        at ir.metrix.sdk.i.b()
        at ir.metrix.sdk.i$y.run()
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by h2soheili** [comment]
این مشکل زمانی اتفاق میفته که 
setAppSecret
هم ست بشه .
یعنی :
setFirebaseAppId +‌setAppSecret =>‌کرش
setFirebaseAppId => بدون کرش
با عدم ست سکرت
. کرش ندارم

پارامتر ها رو به ترتیب وارد کردم . اگر کرش به خاطر ست کردن این سکرت هست چرا روی فایربیس آی دی ایراد گرفته.

برای فایربیس
SHA certificate fingerprint
ست نکردم.
کامنتی ندارید ؟

**Comment by mzmatin** [comment]
لطفا قطعه کد 
initialize
کتابخونه رو ارسال کنید.

**Comment by h2soheili** [comment]
```
import * as React from 'react';
import {View, Text} from 'react-native';
import {Metrix, MetrixConfig} from '@metrixorg/react-native-metrix';
class App extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {};
    const metrixConfig = new MetrixConfig('');
    metrixConfig.setFirebaseAppId(
      '',
    );
    metrixConfig.setAppSecret(
      '1',
      ' ',
      ' ',
      ' ',
      ' ',
    );
    metrixConfig.setLocationListening(true);
    Metrix.onCreate(metrixConfig);
    // console.log('log:::metrix', Metrix);
    // Metrix.getSessionNum(function(sessionNum) {
    //   console.log('log:::metrix sessionNum', sessionNum);
    // });
  }
  render() {
    return (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Text>Hello World</Text>
      </View>
    );
  }
}

export default App;

```

**Comment by mzmatin** [comment]
نسخه 
0.15.4
رو استفاده و تست کنید.
توی این نسخه متد
```
metrixConfig.setFirebaseAppId('<firebaseAppId>');
```
به متد زیر تغییر پیدا کرده:
```
metrixConfig.setFirebaseId('<firebaseAppId>', '<firebaseProjectId>', '<firebaseApiKey>');
```

**Comment by h2soheili** [comment]
الان کرش ندارم ولی دیگه نصب ها نمیفته.
چند تا شبیه ساز ساختم (بدون و با گوگل پلی سرویس)
و تو گوشی واعی هم تست کردم ولی نصب تو داشبورد افزایش پیدا نمیکنه.
تو لاگ کت 
```
6-27 09:59:41.944 4145-4259/com.daapapp.crmrn I/MX_SDK_Core: Logged event to Metrix: session_start
06-27 09:59:56.618 4145-4259/com.daapapp.crmrn I/MX_SDK_Core: Logged event to Metrix: session_stop
```
رو دارم 

اصلا نیازی  به گوگل سرویس برای شمارش نصب داره ؟
قاعدتا باید بدون اون هم باید کنه.

**Comment by mzmatin** [comment]
بسیار خوب. من این issue رو میبندم.
در صورتی که مسئله‌ای درباره آمار وجود دارد با پشتیبانی جداگانه در تماس باشید.
